// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "chatMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {

namespace {

const ::google::protobuf::Descriptor* loginServer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  loginServer_reflection_ = NULL;
const ::google::protobuf::Descriptor* dialogMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  dialogMsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* heartCmd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  heartCmd_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* XY_ID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_chatMsg_2eproto() {
  protobuf_AddDesc_chatMsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "chatMsg.proto");
  GOOGLE_CHECK(file != NULL);
  loginServer_descriptor_ = file->message_type(0);
  static const int loginServer_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(loginServer, xyid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(loginServer, userid_),
  };
  loginServer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      loginServer_descriptor_,
      loginServer::default_instance_,
      loginServer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(loginServer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(loginServer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(loginServer));
  dialogMsg_descriptor_ = file->message_type(1);
  static const int dialogMsg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(dialogMsg, xyid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(dialogMsg, dialogstr_),
  };
  dialogMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      dialogMsg_descriptor_,
      dialogMsg::default_instance_,
      dialogMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(dialogMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(dialogMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(dialogMsg));
  heartCmd_descriptor_ = file->message_type(2);
  static const int heartCmd_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(heartCmd, xyid_),
  };
  heartCmd_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      heartCmd_descriptor_,
      heartCmd::default_instance_,
      heartCmd_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(heartCmd, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(heartCmd, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(heartCmd));
  XY_ID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_chatMsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    loginServer_descriptor_, &loginServer::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    dialogMsg_descriptor_, &dialogMsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    heartCmd_descriptor_, &heartCmd::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_chatMsg_2eproto() {
  delete loginServer::default_instance_;
  delete loginServer_reflection_;
  delete dialogMsg::default_instance_;
  delete dialogMsg_reflection_;
  delete heartCmd::default_instance_;
  delete heartCmd_reflection_;
}

void protobuf_AddDesc_chatMsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rchatMsg.proto\022\010protocol\"H\n\013loginServer"
    "\022)\n\004XYID\030\001 \001(\0162\017.protocol.XY_ID:\nXYID_LO"
    "GIN\022\016\n\006userID\030\002 \001(\t\"J\n\tdialogMsg\022*\n\004XYID"
    "\030\001 \001(\0162\017.protocol.XY_ID:\013XYID_DIALOG\022\021\n\t"
    "dialogStr\030\002 \001(\t\"5\n\010heartCmd\022)\n\004XYID\030\001 \001("
    "\0162\017.protocol.XY_ID:\nXYID_HEART*[\n\005XY_ID\022"
    "\016\n\tMIN_XY_ID\020\220N\022\017\n\nXYID_LOGIN\020\221N\022\020\n\013XYID"
    "_DIALOG\020\222N\022\017\n\nXYID_HEART\020\223N\022\016\n\tMAX_XY_ID"
    "\020\230u", 323);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "chatMsg.proto", &protobuf_RegisterTypes);
  loginServer::default_instance_ = new loginServer();
  dialogMsg::default_instance_ = new dialogMsg();
  heartCmd::default_instance_ = new heartCmd();
  loginServer::default_instance_->InitAsDefaultInstance();
  dialogMsg::default_instance_->InitAsDefaultInstance();
  heartCmd::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_chatMsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_chatMsg_2eproto {
  StaticDescriptorInitializer_chatMsg_2eproto() {
    protobuf_AddDesc_chatMsg_2eproto();
  }
} static_descriptor_initializer_chatMsg_2eproto_;
const ::google::protobuf::EnumDescriptor* XY_ID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return XY_ID_descriptor_;
}
bool XY_ID_IsValid(int value) {
  switch(value) {
    case 10000:
    case 10001:
    case 10002:
    case 10003:
    case 15000:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int loginServer::kXYIDFieldNumber;
const int loginServer::kUserIDFieldNumber;
#endif  // !_MSC_VER

loginServer::loginServer()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void loginServer::InitAsDefaultInstance() {
}

loginServer::loginServer(const loginServer& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void loginServer::SharedCtor() {
  _cached_size_ = 0;
  xyid_ = 10001;
  userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

loginServer::~loginServer() {
  SharedDtor();
}

void loginServer::SharedDtor() {
  if (userid_ != &::google::protobuf::internal::kEmptyString) {
    delete userid_;
  }
  if (this != default_instance_) {
  }
}

void loginServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* loginServer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return loginServer_descriptor_;
}

const loginServer& loginServer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chatMsg_2eproto();
  return *default_instance_;
}

loginServer* loginServer::default_instance_ = NULL;

loginServer* loginServer::New() const {
  return new loginServer;
}

void loginServer::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    xyid_ = 10001;
    if (has_userid()) {
      if (userid_ != &::google::protobuf::internal::kEmptyString) {
        userid_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool loginServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.XY_ID XYID = 1 [default = XYID_LOGIN];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::protocol::XY_ID_IsValid(value)) {
            set_xyid(static_cast< ::protocol::XY_ID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_userID;
        break;
      }

      // optional string userID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_userID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_userid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->userid().data(), this->userid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void loginServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_LOGIN];
  if (has_xyid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->xyid(), output);
  }

  // optional string userID = 2;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->userid().data(), this->userid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->userid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* loginServer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_LOGIN];
  if (has_xyid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->xyid(), target);
  }

  // optional string userID = 2;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->userid().data(), this->userid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->userid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int loginServer::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .protocol.XY_ID XYID = 1 [default = XYID_LOGIN];
    if (has_xyid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->xyid());
    }

    // optional string userID = 2;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->userid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void loginServer::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const loginServer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const loginServer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void loginServer::MergeFrom(const loginServer& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_xyid()) {
      set_xyid(from.xyid());
    }
    if (from.has_userid()) {
      set_userid(from.userid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void loginServer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void loginServer::CopyFrom(const loginServer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool loginServer::IsInitialized() const {

  return true;
}

void loginServer::Swap(loginServer* other) {
  if (other != this) {
    std::swap(xyid_, other->xyid_);
    std::swap(userid_, other->userid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata loginServer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = loginServer_descriptor_;
  metadata.reflection = loginServer_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int dialogMsg::kXYIDFieldNumber;
const int dialogMsg::kDialogStrFieldNumber;
#endif  // !_MSC_VER

dialogMsg::dialogMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void dialogMsg::InitAsDefaultInstance() {
}

dialogMsg::dialogMsg(const dialogMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void dialogMsg::SharedCtor() {
  _cached_size_ = 0;
  xyid_ = 10002;
  dialogstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

dialogMsg::~dialogMsg() {
  SharedDtor();
}

void dialogMsg::SharedDtor() {
  if (dialogstr_ != &::google::protobuf::internal::kEmptyString) {
    delete dialogstr_;
  }
  if (this != default_instance_) {
  }
}

void dialogMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* dialogMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return dialogMsg_descriptor_;
}

const dialogMsg& dialogMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chatMsg_2eproto();
  return *default_instance_;
}

dialogMsg* dialogMsg::default_instance_ = NULL;

dialogMsg* dialogMsg::New() const {
  return new dialogMsg;
}

void dialogMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    xyid_ = 10002;
    if (has_dialogstr()) {
      if (dialogstr_ != &::google::protobuf::internal::kEmptyString) {
        dialogstr_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool dialogMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.XY_ID XYID = 1 [default = XYID_DIALOG];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::protocol::XY_ID_IsValid(value)) {
            set_xyid(static_cast< ::protocol::XY_ID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dialogStr;
        break;
      }

      // optional string dialogStr = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dialogStr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dialogstr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->dialogstr().data(), this->dialogstr().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void dialogMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_DIALOG];
  if (has_xyid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->xyid(), output);
  }

  // optional string dialogStr = 2;
  if (has_dialogstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->dialogstr().data(), this->dialogstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->dialogstr(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* dialogMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_DIALOG];
  if (has_xyid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->xyid(), target);
  }

  // optional string dialogStr = 2;
  if (has_dialogstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->dialogstr().data(), this->dialogstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->dialogstr(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int dialogMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .protocol.XY_ID XYID = 1 [default = XYID_DIALOG];
    if (has_xyid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->xyid());
    }

    // optional string dialogStr = 2;
    if (has_dialogstr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->dialogstr());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void dialogMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const dialogMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const dialogMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void dialogMsg::MergeFrom(const dialogMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_xyid()) {
      set_xyid(from.xyid());
    }
    if (from.has_dialogstr()) {
      set_dialogstr(from.dialogstr());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void dialogMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void dialogMsg::CopyFrom(const dialogMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool dialogMsg::IsInitialized() const {

  return true;
}

void dialogMsg::Swap(dialogMsg* other) {
  if (other != this) {
    std::swap(xyid_, other->xyid_);
    std::swap(dialogstr_, other->dialogstr_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata dialogMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = dialogMsg_descriptor_;
  metadata.reflection = dialogMsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int heartCmd::kXYIDFieldNumber;
#endif  // !_MSC_VER

heartCmd::heartCmd()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void heartCmd::InitAsDefaultInstance() {
}

heartCmd::heartCmd(const heartCmd& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void heartCmd::SharedCtor() {
  _cached_size_ = 0;
  xyid_ = 10003;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

heartCmd::~heartCmd() {
  SharedDtor();
}

void heartCmd::SharedDtor() {
  if (this != default_instance_) {
  }
}

void heartCmd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* heartCmd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return heartCmd_descriptor_;
}

const heartCmd& heartCmd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_chatMsg_2eproto();
  return *default_instance_;
}

heartCmd* heartCmd::default_instance_ = NULL;

heartCmd* heartCmd::New() const {
  return new heartCmd;
}

void heartCmd::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    xyid_ = 10003;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool heartCmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.XY_ID XYID = 1 [default = XYID_HEART];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::protocol::XY_ID_IsValid(value)) {
            set_xyid(static_cast< ::protocol::XY_ID >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void heartCmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_HEART];
  if (has_xyid()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->xyid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* heartCmd::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .protocol.XY_ID XYID = 1 [default = XYID_HEART];
  if (has_xyid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->xyid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int heartCmd::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .protocol.XY_ID XYID = 1 [default = XYID_HEART];
    if (has_xyid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->xyid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void heartCmd::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const heartCmd* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const heartCmd*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void heartCmd::MergeFrom(const heartCmd& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_xyid()) {
      set_xyid(from.xyid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void heartCmd::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void heartCmd::CopyFrom(const heartCmd& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool heartCmd::IsInitialized() const {

  return true;
}

void heartCmd::Swap(heartCmd* other) {
  if (other != this) {
    std::swap(xyid_, other->xyid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata heartCmd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = heartCmd_descriptor_;
  metadata.reflection = heartCmd_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)
